branches:
 only:
  - develop
  - master

git:
 depth: 1

language: csharp
solution: Simplify.Web.Json.sln

script:
 - xbuild /p:Platform="Any CPU" /p:Configuration=Release Simplify.Web.Json.sln /tv:12.0
